apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kube-sc
provisioner: kubernetes.io/no-provisioner # Manual provisioning
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kube-sc
  hostPath:
    path: "/mnt/data" # Local path on the node